name: Build and test Terraform code
run-name: Plan Terraform Actions ; Check Policy ; Apply Terraform Changes
on: [push]
jobs:
  Runner:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2

#     fetch the opa_policy_list_action

      - name: Check out policy repository
        uses: actions/checkout@v3
        with:
          repository: sduff/opa_policy_repo

      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

